version: '3.8'
services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
